spring:
  datasource:
    url: jdbc:postgresql://database:5432/fstock_dev

example:
  property: I AM DEV FROM GIT

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh
  endpoint:
    health:
      show-details: always
