spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fstock_dev
    username: postgres
    password: '{cipher}800e203172405d52235fe09056fbf2eef2433a38ed86a41008209c0c5c64155b'

example:
  property: I AM DEV FROM GIT

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh
  endpoint:
    health:
      show-details: always
