version: '2.1'

services:
  config-server:
    image: config-server
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"

  license-service:
    image: license-service
    container_name: license-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8071
    depends_on:
      config-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "license-service"

networks:
  backend:
    driver: bridge