CREATE TABLE IF NOT EXISTS public.organizations
(
    organization_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL,
    contact_name    VARCHAR(100) NOT NULL,
    contact_email   VARCHAR(100) NOT NULL,
    contact_phone   VARCHAR(20)  NOT NULL,
    CONSTRAINT organizations_pkey PRIMARY KEY (organization_id)
) TABLESPACE pg_default;

ALTER TABLE public.organizations
    OWNER to postgres;

CREATE SEQUENCE IF NOT EXISTS public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1;

ALTER SEQUENCE public.organizations_id_seq
    OWNED BY public.organizations.organization_id;


CREATE TABLE IF NOT EXISTS public.licenses
(
    license_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    organization_id BIGINT       NOT NULL,
    description     VARCHAR(255),
    product_name    VARCHAR(100) NOT NULL,
    license_type    VARCHAR(100) NOT NULL,
    comment         VARCHAR(255),
    CONSTRAINT licenses_pkey PRIMARY KEY (license_id),
    CONSTRAINT licenses_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES public.organizations (organization_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID
) TABLESPACE pg_default;

ALTER TABLE public.licenses
    OWNER to postgres;

CREATE SEQUENCE IF NOT EXISTS public.licenses_id_seq
    START WITH 1
    INCREMENT BY 1;

ALTER SEQUENCE public.licenses_id_seq
    OWNED BY public.licenses.license_id;
