server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/fstock_dev
    username: postgres
    password: '{cipher}831b0afbf77bd60d012e6f22efb2aff6dd4cfd501cc97296cc58afdfc47da2a3'

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka
