server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/fstock_dev
    username: postgres
    password: '{cipher}831b0afbf77bd60d012e6f22efb2aff6dd4cfd501cc97296cc58afdfc47da2a3'

  kafka:
    admin:
      bootstrap.servers: kafka:29092
    bootstrap-servers: kafka:29092
  cloud.stream:
    bindings:
      output-org-0:
        destination: orgChangeTopic
        content-type: application/json
    kafka.binder:
      brokers: kafka

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka

keycloak:
  realm: format-realm
  auth-server-url: http://keycloak:8080
  ssl-required: none
  resource: fstock
  credentials.secret: 6knWgXi0cnsjQ55MQuZpRSy6bMmu0y5W
  use-resource-role-mappings: true
  bearer-only: true
