spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fstock_dev
    password: '{cipher}78cb416c3b2d6aa1e87638cd32ccdee2b93f764051404d6d95ee005eb12744d5'

example:
  property: I AM LOCAL FROM GIT

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh
  endpoint:
    health:
      show-details: always
