server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8070/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
            - RemoveRequestHeader= Cookie,Set-Cookie

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env,refresh,bus-refresh,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true