spring:
  application:
    name: config-server
  profiles:
    active:
      - native, git
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
        git:
          uri: https://github.com/FormAToz/microservice_demo.git
          search-paths:
            - config/{application}
            - config/{application}/{profile}
          default-label: develop

server:
  port: 8071
