spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fstock_dev
    username: postgres
    password: postgres

example:
  property: I AM DEV

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,env
  endpoint:
    health:
      show-details: always